db_host: "{{ db_address }}"
db_name: "{{ db_database }}"
db_user: "{{ db_username }}"
db_password: "{{ db_password }}"
db_port: "{{ db_port }}"
datadog_api_key: "{{ datadog_api_key }}"
datadog_site: datadoghq.eu
site_base_url: http://77.makovetskiy.xyz
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: http_check
        url: "{{ site_base_url }}"
        timeout: 5
        method: GET
